sonar.projectKey=javiyt_gridirontimer
sonar.organization=javiyt
sonar.projectName=GridironTimer

# Paths
sonar.sources=app/src/main
sonar.tests=app/src/test

# Language
sonar.language=kotlin
sonar.kotlin.file.suffixes=.kt

# Coverage
sonar.coverageReportPaths=app/build/reports/kover/reportDebug.xml
sonar.coverage.exclusions=**/*Composable*,**/presentation/views/**,**/presentation/theme/**

# Execution paths 
sonar.java.binaries=app/build/intermediates/compile_app_classes_jar/debug

# Issue exclusions
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=kotlin:S1874
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*.kt
